### PR TITLE
fix(init): skip modules that are dependencies of other modules

### LINKED ISSUE #875: Never install `@nuxt/fonts` or `@nuxt/icon` if `@nuxt/ui` is selected
In the wizard for init a project, if the user ticks one of the official modules that is already installed by default by @nuxt/ui, the module should not be installed because it is not useful in the first place and in some cases it may bug the configurations applied by default by nuxt/ui.

https://github.com/nuxt/cli/blob/main/packages/nuxi/src/commands/init.ts#L270

### PR DESCRIPTION
**Pull request by HugoRCD**
### 🔗 Linked issue

Resolves #875 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

File: packages/nuxi/src/commands/init.ts [hunk 1]
```diff
@@ -297,7 +334,19 @@ export default defineCommand({
         }
 
         if (selectedOfficialModules.length > 0) {
-          modulesToAdd.push(...(selectedOfficialModules as unknown as string[]))
+          const modules = selectedOfficialModules as unknown as string[]
+
+          const allDependencies: Record<string, string[]> = {}
+          for (const module of modules) {
+            allDependencies[module] = await getModuleDependencies(module)
```
Comment (danielroe) [inline packages/nuxi/src/commands/init.ts]: we probably also want to get the dependencies of the template that's been installed (and not prompt to install any modules it contains), but that can be for another pr

for example, if you run `pnpm create nuxt -t ui`, it probably should not prompt to install `@nuxt/fonts`.

**Review by danielroe — APPROVED** [review]

File: packages/nuxi/src/commands/init.ts (hunk 1 above)
Comment (HugoRCD) [reply packages/nuxi/src/commands/init.ts]: I'll try to make a PR for that too!
