### PR TITLE
fix(add): respect custom dirs from nuxt project

### LINKED ISSUE #551: Nuxt 4 Directory structure support
Nuxt is getting ready for v4: https://github.com/nuxt/nuxt/pull/27029

Are there plans to support the new folder structure?

**Issue**
I ran in to an issue attempting to add a new api route:
`npx nuxi@latest add api issues --get`

This will add to `./app/server/api/`, but my server and api directory is in `./server/api`. This is because the file is written to [config.srcDir](https://github.com/nuxt/cli/blob/main/src/commands/add.ts#L66)

**Reproduction:**
1. Clone https://github.com/nuxt-hub/starter
2. Run `npx nuxi@latest add api issues --get`
3. Note that the new api is added to `app/server/api` and not `/server/api`

**Possible Solutions**
- Utilize the [config.serverDir](https://nuxt.com/docs/api/nuxt-config#serverdir) when operating on server files. 
- Detect [nuxt 4 compatibility version](https://nuxt.com/docs/getting-started/upgrade#opting-in-to-nuxt-4)

### PR DESCRIPTION
**Pull request by BobbieGoede**
### 🔗 Linked issue
* #551 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Resolves #551 

Changes the generated api template path to be resolved from `rootDir` instead of `srcDir` if `compatibilityVersion: 4`, not sure if other templates should be from `rootDir` as well, let me know.

I also changed the template paths to use the config `dir` where applicable, not sure if there's an open issue for this 🤔

### CODE REVIEW

File: src/commands/add.ts [hunk 1]
```diff
@@ -61,10 +61,13 @@ export default defineCommand({
...
     // Resolve template
-    const res = template({ name, args: ctx.args })
+    const res = template({ name, args: ctx.args, nuxt: config })
+
+    // Change resolution root dir when applicable
+    const resolveFromRoot = config.future.compatibilityVersion === 4 && templateName === 'api'
 
     // Resolve full path to generated file
-    const path = resolve(config.srcDir, res.path)
+    const path = resolve(resolveFromRoot ? config.rootDir : config.srcDir, res.path)
```
Comment (danielroe) [inline src/commands/add.ts:70]: I think we can safely always resolve from `config.srcDir`, even without `compatibilityVersion: 4`, as it's always been possible to set a custom `srcDir`...

The only exception is modules, server, etc. But this bug _already_ exists and probably needs another solution (e.g. specifying in template somehow whether it is relative to srcDir or rootDir.

Comment (BobbieGoede) [reply src/commands/add.ts]: I've changed it now so that the full path is resolved from within the template function. I suppose this will be easier to expand if we will add templates for the other exceptions you mention.

File: src/utils/templates.ts [hunk 2]
```diff
@@ -20,28 +23,32 @@ const httpMethods = [
...
 ]
-const api: Template = ({ name, args }) => ({
-  path: `server/api/${name}${applySuffix(args, httpMethods, 'method')}.ts`,
-  contents: `
+const api: Template = ({ name, args, nuxt }) => {
+  const pathRoot = nuxt.future.compatibilityVersion === 4 ? nuxt.rootDir : nuxt.srcDir
+
+  return {
+    path: resolve(pathRoot, `${nuxt.serverDir}/api/${name}${applySuffix(args, httpMethods, 'method')}.ts`),
+    contents: `
```
Comment (danielroe) [inline src/utils/templates.ts:31]:
```suggestion
  return {
    path: resolve(nuxt.srcDir, nuxt.serverDir, `api/${name}${applySuffix(args, httpMethods, 'method')}.ts`),
    contents: `
```

File: src/utils/templates.ts [hunk 3]
```diff
@@ -20,28 +23,32 @@ const httpMethods = [
...
 })
 `,
-})
+  }
+}
 
-const plugin: Template = ({ name, args }) => ({
-  path: `plugins/${name}${applySuffix(args, ['client', 'server'], 'mode')}.ts`,
+const plugin: Template = ({ name, args, nuxt }) => ({
+  path: resolve(nuxt.srcDir, `${nuxt.dir.plugins}/${name}${applySuffix(args, ['client', 'server'], 'mode')}.ts`),
```
Comment (danielroe) [inline src/utils/templates.ts:40]:
```suggestion
  path: resolve(nuxt.srcDir, nuxt.dir.plugins, `${name}${applySuffix(args, ['client', 'server'], 'mode')}.ts`),
```

File: src/utils/templates.ts [hunk 4]
```diff
@@ -69,15 +76,15 @@ export const composable: Template = ({ name }) => {
   }
 }
 
-const middleware: Template = ({ name, args }) => ({
-  path: `middleware/${name}${applySuffix(args, ['global'])}.ts`,
+const middleware: Template = ({ name, args, nuxt }) => ({
+  path: resolve(nuxt.srcDir, `${nuxt.dir.middleware}/${name}${applySuffix(args, ['global'])}.ts`),
```
Comment (danielroe) [inline src/utils/templates.ts:80]:
```suggestion
  path: resolve(nuxt.srcDir, nuxt.dir.middleware, `${name}${applySuffix(args, ['global'])}.ts`),
```

File: src/utils/templates.ts [hunk 5]
```diff
@@ -69,15 +76,15 @@ export const composable: Template = ({ name }) => {
...
   contents: `
 export default defineNuxtRouteMiddleware((to, from) => {})
 `,
 })
 
-const layout: Template = ({ name }) => ({
-  path: `layouts/${name}.vue`,
+const layout: Template = ({ name, nuxt }) => ({
+  path: resolve(nuxt.srcDir, `${nuxt.dir.layouts}/${name}.vue`),
```
Comment (danielroe) [inline src/utils/templates.ts:87]:
```suggestion
  path: resolve(nuxt.srcDir, nuxt.dir.layouts, `${name}.vue`),
```

File: src/utils/templates.ts [hunk 6]
```diff
@@ -92,8 +99,8 @@ const layout: Template = ({ name }) => ({
 `,
 })
 
-const page: Template = ({ name }) => ({
-  path: `pages/${name}.vue`,
+const page: Template = ({ name, nuxt }) => ({
+  path: resolve(nuxt.srcDir, `${nuxt.dir.pages}/${name}.vue`),
```
Comment (danielroe) [inline src/utils/templates.ts:103]:
```suggestion
  path: resolve(nuxt.srcDir, nuxt.dir.pages, `${name}.vue`),
```

File: src/utils/templates.ts [hunk 7]
```diff
@@ -1,8 +1,11 @@
+import { resolve } from 'pathe'
 import { camelCase, upperFirst } from 'scule'
+import type { NuxtOptions } from '@nuxt/schema'
 
 interface TemplateOptions {
   name: string
   args: Record<string, any>
+  nuxt: NuxtOptions
```
Comment (danielroe) [inline src/utils/templates.ts:8]: might be clearer to rename this `nuxtOptions`

**Review by danielroe — COMMENTED** [review]
looks like we also need to update the tests to pass the config

File: src/utils/templates.ts (hunk 2 above)
Comment (BobbieGoede) [reply src/utils/templates.ts]: > ... the serverDir is absolute ...

Ah I see, I thought it was a relative path!
